### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by SadLandscape** [Xefer-0/DiscordGrabber#2]
Title says all
Thanks

**Comment by K3maaa** [comment]
javac <the .jar files>jar

**Comment by SadLandscape** [comment]
> javac <the .jar files>jar

I did not quite get that and I'm not experienced in java programming can you please give me more detailed guide?
Thanks a lot.

**Comment by B4RC0DE-TM** [comment]
SadLandscape please watch some videos on YT or buy some classes...
